### ISSUE TITLE
Index Page Load Failure on Main Branch Due to Missing demo.js

### ISSUE THREAD

**Issue by wiederholung** [liyang619/COLE-Platform#2]
## Issue

Unable to correctly load the index page on the main branch, which blocks subsequent operations.

## Error Details

Flask reports a "404 Not Found" error for the missing `demo.js`: 

> "GET /static/js/demo/demo.js HTTP/1.1" 404 -

This occurs because the `demo.js` file is absent in the main branch.

## Steps Taken

The `demo.js` file from the `human-human/llm` branch located at `overcookedgym/overcooked-flask/static/js/demo/demo.js` has been copied to the corresponding location on the main branch.

## New Error After Fix

After fixing the missing `demo.js` file, a KeyError occurs on the playtesting page with the message: 

> "POST /bc/predict/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   ...
> File "overcookedgym/overcooked-flask/app.py", line 165, in predict
> data_json["npc_index"],
> KeyError: 'npc_index'

**Comment by Bluixe** [comment]
Thanks for your asking.
I think you may missed some part of the README.md

In the "1. How to setup" of "Getting Started", these is a sequence of command you need to run such as "npm install" and "npm run build". That is to build the overcooked_ai game core.

Indeed, in the human-human/llm branch, I leave the demo.js in it. However, this demo.js is different from the built demo.js in main branch, that's why I said you need to re-run the "npm build". I'm so sorry that I didn't express it more clearly, which makes you confuse.

**Comment by wiederholung** [comment]
> Thanks for your asking. I think you may missed some part of the README.md
> 
> In the "1. How to setup" of "Getting Started", these is a sequence of command you need to run such as "npm install" and "npm run build". That is to build the overcooked_ai game core.
> 
> Indeed, in the human-human/llm branch, I leave the demo.js in it. However, this demo.js is different from the built demo.js in main branch, that's why I said you need to re-run the "npm build". I'm so sorry that I didn't express it more clearly, which makes you confuse.

It works, thanks for the reminder.
